## Regenerates the synthetic example assets shipped in inst/extdata. The data
## are invented, not derived from any experiment, and exist only so that
## examples, tests and the vignette have something fast and deterministic to
## run on.
##
## Run from the package root:
##   source("inst/scripts/make-example-data.R")
##
## Files written:
## - example_sample_data.csv: 20 samples, 10 Recovered and 10 PASC.
## - example_protein_abundance.csv: 5 proteins.
## - example_transcript_abundance.csv: 5 transcripts.
## - example_metabolite_abundance.csv: 4 metabolites.
##
## example_knowledge_network.csv and example_seed_nodes.txt are hand-written and
## are not regenerated here.
##
## Ten samples per group is deliberate. The Fisher z difference divides by
## (n - 3), so the four-per-group data used before version 0.99.2 gave the test
## a standard error of sqrt(2) and made every example inferentially meaningless.
## Ten is the threshold below which CorNetto itself warns.
##
## Values come from a small linear congruential generator rather than rnorm() so
## that the CSVs can be regenerated byte-for-byte on any platform and in any
## language, independent of R's RNG stream.

## Set `outputDir` before sourcing to write somewhere else, which is how
## check-package.R verifies that this script still reproduces the shipped CSVs.
if (!exists("outputDir")) {
    outputDir <- file.path("inst", "extdata")
}
groupSize <- 10L

lcgState <- 1L
nextUniform <- function() {
    lcgState <<- (25173L * lcgState + 13849L) %% 65536L
    lcgState / 65536
}
jitter <- function(scale) (nextUniform() - 0.5) * scale

## Latent driver, roughly -1.5 to 1.5 across the samples of a group.
latent <- function(i) (i - (groupSize + 1) / 2) / 3.03

## feature = intercept + slope * latent + noise, with the slope and noise width
## allowed to differ by group. Pairs that share a driver correlate; pairs whose
## slope collapses in one group are the rewiring signal the vignette looks for.
buildFeature <- function(intercept, slopeRecovered, noiseRecovered,
                         slopePASC, noisePASC) {
    recovered <- vapply(
        seq_len(groupSize),
        function(i) intercept + slopeRecovered * latent(i) + jitter(noiseRecovered),
        numeric(1L)
    )
    pasc <- vapply(
        seq_len(groupSize),
        function(i) intercept + slopePASC * latent(i) + jitter(noisePASC),
        numeric(1L)
    )
    round(c(recovered, pasc), 3L)
}

sampleIds <- c(paste0("R", seq_len(groupSize)), paste0("P", seq_len(groupSize)))

sampleData <- data.frame(
    sampleId = sampleIds,
    clinicalGroup = rep(c("Recovered", "PASC"), each = groupSize),
    visit = "Visit2",
    stringsAsFactors = FALSE
)

writeAssay <- function(fileName, identifiers, displayNames, rows) {
    assayTable <- data.frame(
        featureIdentifier = identifiers,
        featureName = displayNames,
        stringsAsFactors = FALSE
    )
    values <- as.data.frame(do.call(rbind, rows), stringsAsFactors = FALSE)
    names(values) <- sampleIds
    utils::write.csv(
        cbind(assayTable, values),
        file.path(outputDir, fileName),
        row.names = FALSE,
        quote = FALSE
    )
}

## Proteins. P1-P2 carry the headline rewiring: tightly coupled in Recovered,
## decoupled in PASC. P5 flips sign between groups.
writeAssay(
    "example_protein_abundance.csv",
    c("P1", "P2", "P3", "P4", "P5"),
    c("CFH", "C3", "CR1", "CFB", "C5"),
    list(
        buildFeature(12.0, 1.00, 1.2, 1.00, 1.2),
        buildFeature(11.5, 0.95, 1.2, 0.05, 1.5),
        buildFeature(10.8, 0.60, 1.3, 0.70, 1.3),
        buildFeature(10.0, 0.20, 1.8, 0.20, 1.8),
        buildFeature(9.5, -0.90, 1.2, 0.90, 1.2)
    )
)

## Transcripts. T1 tracks P1 so the central-dogma prior edge has signal; T1-T2
## rewire in the same direction as P1-P2.
writeAssay(
    "example_transcript_abundance.csv",
    c("T1", "T2", "T3", "T4", "T5"),
    c("CFH transcript", "C3 transcript", "CR1 transcript",
      "CFB transcript", "C5 transcript"),
    list(
        buildFeature(8.0, 0.90, 1.2, 0.90, 1.2),
        buildFeature(7.6, 0.90, 1.2, 0.10, 1.5),
        buildFeature(7.2, 0.50, 1.4, 0.55, 1.4),
        buildFeature(6.9, 0.15, 1.8, 0.15, 1.8),
        buildFeature(6.5, 0.40, 1.5, 0.45, 1.5)
    )
)

## Metabolites. M2-P2 gains coupling in PASC, the opposite direction to P1-P2.
writeAssay(
    "example_metabolite_abundance.csv",
    c("M1", "M2", "M3", "M4"),
    c("Citrate", "Succinate", "Fumarate", "Malate"),
    list(
        buildFeature(6.0, 0.80, 1.2, 0.80, 1.2),
        buildFeature(5.5, 0.20, 1.5, 0.90, 1.2),
        buildFeature(5.1, 0.45, 1.5, 0.45, 1.5),
        buildFeature(4.8, 0.10, 1.8, 0.10, 1.8)
    )
)

utils::write.csv(
    sampleData,
    file.path(outputDir, "example_sample_data.csv"),
    row.names = FALSE,
    quote = FALSE
)
